name: pmvvm
description: A clean & simple MVVM solution for state management using Provider package.
version: 4.0.1
homepage: https://github.com/NourEldinShobier/pmvvm

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  provider: ^6.0.2
  flutter_hooks: ^0.18.3
  tint: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  # For Analyzer
  effective_dart: ^1.3.1

  flutter_test:
    sdk: flutter

flutter:
