name: pmvvm
description: A clean & simple MVVM solution for state management using Provider package.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^4.3.1
  flutter_hooks: ^0.12.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: