name: pmvvm
description: A clean & simple MVVM solution for state management using Provider package.
version: 2.0.0
homepage: https://github.com/NourEldinShobier/pmvvm

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  provider: ^5.0.0
  flutter_hooks: ^0.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: