name: pmvvm
description: A clean & simple MVVM solution for state management using Provider package.
version: 1.0.0
homepage: https://github.com/NourEldinShobier/pmvvm

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^4.3.2+2
  flutter_hooks: ^0.14.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: